apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 992e1533702410f2816ece75ce4a2af8f4a0f5ea
    app.openshift.io/vcs-uri: https://github.com/davidbieder/fullstack-backend-with-database
  labels:
    app.kubernetes.io/instance: backend
    app.kubernetes.io/name: backend
  name: backend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: backend
    app.kubernetes.io/name: backend
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 992e1533702410f2816ece75ce4a2af8f4a0f5ea
    app.openshift.io/vcs-uri: https://github.com/davidbieder/fullstack-backend-with-database
  labels:
    app.kubernetes.io/instance: backend
    app.kubernetes.io/name: backend
  name: backend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: backend
      app.kubernetes.io/name: backend
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 992e1533702410f2816ece75ce4a2af8f4a0f5ea
        app.openshift.io/vcs-uri: https://github.com/davidbieder/fullstack-backend-with-database
      labels:
        app.kubernetes.io/instance: backend
        app.kubernetes.io/name: backend
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        - name: DATABASE_URL
          value: postgres://user:password@postgresql:5432/db
        image: quay.io/davidbieder/fullstack-backend-with-database:992e1533702410f2816ece75ce4a2af8f4a0f5ea
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: backend
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 992e1533702410f2816ece75ce4a2af8f4a0f5ea
    app.openshift.io/vcs-uri: https://github.com/davidbieder/fullstack-backend-with-database
  labels:
    app.kubernetes.io/instance: backend
    app.kubernetes.io/name: backend
  name: backend
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: backend
    weight: 100
  wildcardPolicy: None
