apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: fa8448fbce4251c41c6ae9ef03872e22bead52c0
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/next-js-lev-andrejev
  labels:
    app.kubernetes.io/instance: my-nextjs-app
    app.kubernetes.io/name: my-nextjs-app
  name: my-nextjs-app-svc
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: my-nextjs-app
    app.kubernetes.io/name: my-nextjs-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: fa8448fbce4251c41c6ae9ef03872e22bead52c0
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/next-js-lev-andrejev
  labels:
    app.kubernetes.io/instance: my-nextjs-app
    app.kubernetes.io/name: my-nextjs-app
  name: my-nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-nextjs-app
      app.kubernetes.io/name: my-nextjs-app
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: fa8448fbce4251c41c6ae9ef03872e22bead52c0
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/next-js-lev-andrejev
      labels:
        app.kubernetes.io/instance: my-nextjs-app
        app.kubernetes.io/name: my-nextjs-app
    spec:
      containers:
      - image: quay.io/levandrejev/nextjs-app:fa8448fbce4251c41c6ae9ef03872e22bead52c0
        name: my-nextjs-app
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: fa8448fbce4251c41c6ae9ef03872e22bead52c0
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/next-js-lev-andrejev
  labels:
    app.kubernetes.io/instance: my-nextjs-app
    app.kubernetes.io/name: my-nextjs-app
  name: my-nextjs-app-svc
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: my-nextjs-app-svc
    weight: 100
  wildcardPolicy: None
