apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 61fb1f28350ac3d8f0dc7ae2d4975968db3dd5f2
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea-8-nextjs-app-linjing-tomasz.git
  labels:
    app.kubernetes.io/instance: next-js-app
    app.kubernetes.io/name: next-js-app
  name: next-js-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: next-js-app
    app.kubernetes.io/name: next-js-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 61fb1f28350ac3d8f0dc7ae2d4975968db3dd5f2
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea-8-nextjs-app-linjing-tomasz.git
  labels:
    app.kubernetes.io/instance: next-js-app
    app.kubernetes.io/name: next-js-app
    app.openshift.io/runtime: js
  name: next-js-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: next-js-app
      app.kubernetes.io/name: next-js-app
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 61fb1f28350ac3d8f0dc7ae2d4975968db3dd5f2
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea-8-nextjs-app-linjing-tomasz.git
      labels:
        app.kubernetes.io/instance: next-js-app
        app.kubernetes.io/name: next-js-app
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/fu_linjing/next-app:61fb1f28350ac3d8f0dc7ae2d4975968db3dd5f2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: next-js-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 61fb1f28350ac3d8f0dc7ae2d4975968db3dd5f2
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea-8-nextjs-app-linjing-tomasz.git
  labels:
    app.kubernetes.io/instance: next-js-app
    app.kubernetes.io/name: next-js-app
  name: next-js-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: next-js-app
    weight: 100
  wildcardPolicy: None
