apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 27c8c89554952149e6e1239fe33437bd45142666
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea-8-bernhard-ott-nextjs-app
  labels:
    app.kubernetes.io/instance: nextjs
    app.kubernetes.io/name: nextjs
  name: nextjs
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: nextjs
    app.kubernetes.io/name: nextjs
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 27c8c89554952149e6e1239fe33437bd45142666
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea-8-bernhard-ott-nextjs-app
  labels:
    app.kubernetes.io/instance: nextjs
    app.kubernetes.io/name: nextjs
  name: nextjs
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: nextjs
      app.kubernetes.io/name: nextjs
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 27c8c89554952149e6e1239fe33437bd45142666
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea-8-bernhard-ott-nextjs-app
      labels:
        app.kubernetes.io/instance: nextjs
        app.kubernetes.io/name: nextjs
        app.openshift.io/runtime: js
        app.openshift.io/vcs-ref: bar
        app.openshift.io/vcs-uri: foo
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/bott_ibm/nextjs:27c8c89554952149e6e1239fe33437bd45142666
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nextjs
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 27c8c89554952149e6e1239fe33437bd45142666
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea-8-bernhard-ott-nextjs-app
  labels:
    app.kubernetes.io/instance: nextjs
    app.kubernetes.io/name: nextjs
  name: nextjs
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: nextjs
    weight: 100
  wildcardPolicy: None
