apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: a8ad38abb273f263f308d754c675c1428c4b067b
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/fred-william-tekton-e2e-assignment
  labels:
    app.kubernetes.io/instance: fred-william-nextjs-app
    app.kubernetes.io/name: fred-william-nextjs-app
  name: fred-william-nextjs-app-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: fred-william-nextjs-app
    app.kubernetes.io/name: fred-william-nextjs-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: a8ad38abb273f263f308d754c675c1428c4b067b
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/fred-william-tekton-e2e-assignment
  labels:
    app.kubernetes.io/instance: fred-william-nextjs-app
    app.kubernetes.io/name: fred-william-nextjs-app
    app.openshift.io/runtime: js
  name: fred-william-nextjs-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: fred-william-nextjs-app
      app.kubernetes.io/name: fred-william-nextjs-app
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: a8ad38abb273f263f308d754c675c1428c4b067b
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/fred-william-tekton-e2e-assignment
      labels:
        app.kubernetes.io/instance: fred-william-nextjs-app
        app.kubernetes.io/name: fred-william-nextjs-app
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/faklamanu/fred-william-nextjs-app:a8ad38abb273f263f308d754c675c1428c4b067b
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: fred-william-nextjs-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: a8ad38abb273f263f308d754c675c1428c4b067b
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/fred-william-tekton-e2e-assignment
  labels:
    app.kubernetes.io/instance: fred-william-nextjs-app
    app.kubernetes.io/name: fred-william-nextjs-app
  name: fred-william-nextjs-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: fred-william-nextjs-app-service
    weight: 100
  wildcardPolicy: None
