apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 9229992f89fce176573d22fc1ee01a33d59dfbe3
    app.openshift.io/vcs-uri: https://github.com/davidbieder/postgresql-app
  labels:
    app.kubernetes.io/instance: postgresql-app
    app.kubernetes.io/name: postgresql-app
  name: postgresql-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: postgresql-app
    app.kubernetes.io/name: postgresql-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 9229992f89fce176573d22fc1ee01a33d59dfbe3
    app.openshift.io/vcs-uri: https://github.com/davidbieder/postgresql-app
  labels:
    app.kubernetes.io/instance: postgresql-app
    app.kubernetes.io/name: postgresql-app
  name: postgresql-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: postgresql-app
      app.kubernetes.io/name: postgresql-app
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 9229992f89fce176573d22fc1ee01a33d59dfbe3
        app.openshift.io/vcs-uri: https://github.com/davidbieder/postgresql-app
      labels:
        app.kubernetes.io/instance: postgresql-app
        app.kubernetes.io/name: postgresql-app
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        - name: DATABASE_URL
          value: postgres://user:password@postgresql:5432/db
        image: quay.io/davidbieder/postgresql-app:9229992f89fce176573d22fc1ee01a33d59dfbe3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: postgresql-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 9229992f89fce176573d22fc1ee01a33d59dfbe3
    app.openshift.io/vcs-uri: https://github.com/davidbieder/postgresql-app
  labels:
    app.kubernetes.io/instance: postgresql-app
    app.kubernetes.io/name: postgresql-app
  name: postgresql-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: postgresql-app
    weight: 100
  wildcardPolicy: None
